### ISSUE TITLE
onArrowPress How to use 

### ISSUE THREAD

**Issue by aemre** [NoriginMedia/Norigin-Spatial-Navigation#1]
onArrowPress How to use because is not a callback function.

**Comment by asgvard** [comment]
Hi,

thanks for your question. I have added a bit more info in the docs, indeed it was missing some explanation as this callback is a bit different from the others.
Basically, this callback is called when the component is focused and any arrow key is pressed, but it HAS to return either "true" or "false".
`true` = default behavior - navigation will proceed in the given direction.
`false` = navigation will be blocked.

This callback was created as a "blocker" check, in case you want to manually restrict navigation in certain directions.

As per TS declaration:

```typescript
onArrowPress?: (
    direction: string,
    props: object,
    details: KeyPressDetails
  ) => boolean;
```
