### ISSUE TITLE
Add a function to set key events

### ISSUE THREAD

**Issue by YoavHortman** [NoriginMedia/Norigin-Spatial-Navigation#102]
**Is your feature request related to a problem? Please describe.**
The application I'm building can be controlled both from the keyboard (or tv remote) and from a phone (connected via socket)

**Describe the solution you'd like**
I would like to be able to extend the events that are being listened to, not only the key codes.

**Describe alternatives you've considered**
For now I'm dispatching fake keyboard events when I receive a navigation command from the phone.

**Additional context**
I think it would make sense to do something similar to setKeyMap, but for events.

**Comment by predikament** [comment]
Hello @YoavHortman!

Are you meaning something like this? https://github.com/NoriginMedia/Norigin-Spatial-Navigation#setkeymap

If not then perhaps you could provide some examples or snippets of what and how you are intending to achieve it, so we can better help you out?

**Comment by YoavHortman** [comment]
I think this code example would answer your question:
```
 const commandToEvent: Record<NavigationCommand['command'], KeyboardEvent> = {
      up: new KeyboardEvent('keydown', { bubbles: true, cancelable: true, key: 'ArrowUp', keyCode: 38 }),
      down: new KeyboardEvent('keydown', { bubbles: true, cancelable: true, key: 'ArrowDown', keyCode: 40 }),
      left: new KeyboardEvent('keydown', { bubbles: true, cancelable: true, key: 'ArrowLeft', keyCode: 37 }),
      right: new KeyboardEvent('keydown', {
        bubbles: true,
        cancelable: true,
        key: 'ArrowRight',
        keyCode: 39,
      }),
      enter: new KeyboardEvent('keydown', { bubbles: true, cancelable: true, key: 'Enter', keyCode: 13 }),
      back: new KeyboardEvent('keydown', { bubbles: true, cancelable: true, key: 'Backspace', keyCode: 8 }),
    };
```
```
    communication.receiveNavigationCommand((command) => {
      window.dispatchEvent(commandToEvent[command.command]);
    });
```

Essentially I'm being forced to simulate keyboard events when navigation comes from a different device,

I don't want to change the keymap, I want to add to the set of events that triggers a navigation.
