### ISSUE TITLE
RTL Flag isn't work

### ISSUE THREAD

**Issue by mahmoudjhonny** [NoriginMedia/Norigin-Spatial-Navigation#114]
RTL Flag isn't work. in Init function.......

init({
rtl: true;
})

i try to add this also shouldUseNativeEvents but not any change has shown

what is the previous action should i do before this configuration

**Comment by predikament** [comment]
Hello @mahmoudjhonny, thanks for getting in touch.

Could you please provide some example code snippets of how you are trying to approach this?

#96 is the PR where this functionality was added and it has been tested both internally and externally without issues, so I am unsure what problem you might be facing.

Let us know and we can try to help you out if there's any issues in our library.

**Comment by Braggiouy** [comment]
Hello @mahmoudjhonny,

Thanks for reaching out.

Based on the functionality you're describing, the `rtl` flag in the `init` function does not directly alter the layout/UI. Instead, it changes the navigation system and how focus is calculated. To modify the layout, you will need to manually change the document’s direction by setting `dir="rtl"` in your main HTML structure. Once this is done, the RTL navigation should work as expected.

Additionally, we have an updateRTL method [(Documentation)](https://github.com/NoriginMedia/Norigin-Spatial-Navigation?tab=readme-ov-file#updatertl-function) that allows you to dynamically switch between RTL and LTR navigation without needing to reinitialize the norigin-spatial-navigation service (i.e., no need to call `init` again). This makes it easy to toggle navigation systems on the fly.

I hope this clarifies your doubt! If you still face issues or need further assistance, please share more details (including code snippets), and we’ll be happy to help.
