### ISSUE TITLE
Dynamic RTL switching

### ISSUE THREAD

**Issue by karimlaham** [NoriginMedia/Norigin-Spatial-Navigation#119]
**Is your feature request related to a problem? Please describe.**
My app supports dynamic switching of languages, hence necessitates updating the writingDirection prop of the spacial navigation instance
I want to do so without calling init again   

**Describe the solution you'd like**
I would like to add the bellow function to the SpacialNavigation.ts class
bellow is my suggestion

```
 /**
   * This function updates the writing direction
   * @param rtl whether the writing direction is right-to-left
   */
  updateRtl(rtl: boolean) {
    this.writingDirection = rtl ? WritingDirection.RTL : WritingDirection.LTR;
  }
```

reference to PR with suggested change: https://github.com/NoriginMedia/Norigin-Spatial-Navigation/pull/120

**Comment by predikament** [comment]
#120 has been merged - We'll update and resolve this issue once the new version containing the change has been released.

**Comment by Braggiouy** [comment]
Greetings @karimlaham. Just for you to know, we've just updated the `norigin-spatial-navigation` to version `v2.2.1`, which includes the RTL dynamic switching, as well as other features. You can find a detailed description in the CHANGELOG.md file. 

Thanks, @karimlaham, for creating the suggestion and PR 🎉 

I will proceed and close this issue as completed.
