### ISSUE TITLE
onFocus callback always returns y:0

### ISSUE THREAD

**Issue by maidbarion** [NoriginMedia/Norigin-Spatial-Navigation#12]
Hey all! I've been migrating an app over to your new hooks library, and I've ran into a slight issue - the onFocus callback seems to return y:0 regardless of the elements position. The Dom and component structure are identical to pre-migration, the only difference being the provider. The structure itself is a bunch of focusable rows on top of each other that all share the same parent component. CSS top is calculating correctly, just not y.

Anyway, my question is - are we now calculating x and y differently from the previous HOC library? Has anyone else ran into this problem?

Cheers

**Comment by asgvard** [comment]
Hi!

We haven't changed the way of how the coordinates are calculated.
Keep in mind though, that these coordinates are calculated relatively to the nearest DOM parent, and not to the nearest "focusable" parent component.
My guess is that you might have some kind of DOM wrapper around the element that you assign the "ref" to, this might cause it relative position to be always 0.
Can you provide a code snippet of how your parent + child component looks like?

**Comment by maidbarion** [comment]
Thanks so much for your quick reply to this - good to know the calculations haven't changed. Anyway, the problem component is below...

-hook
```
const { ref } = useFocusable({
    isFocusBoundary: true,
    focusKey
});
```

-structure
```
<div>
      <div>
        <FocusContext.Provider value={focusKey}>
          <motion.div
            ref={ref}
          >
            {condition1 && (
              <FocusableElement
                focusKey="FOCUS-KEY-1"
                onFocus={onFocusRow}
              />
            )}
            {condition2 && (
              <FocusableElement
                focusKey="FOCUS-KEY-2"
                onFocus={onFocusRow}
              />
            )}
            {condition3 && (
              <FocusableElement
                focusKey="FOCUS-KEY-3"
                onFocus={onFocusRow}
              />
            )}
            {condition4 && (
              <FocusableElement
                focusKey="FOCUS-KEY-4"
                onFocus={onFocusRow}
              />
            )}
          </motion.div>
        </FocusContext.Provider>
      </div>
    </div>
```

-callback
```
const onFocusRow = (item) => {
    console.log(item);
};
```

It's probably worth pointing out this is nested 3 components deep and has quite a few children, too. I've tried restructuring this by adding a buffer div between ref and focusable elements, and also by playing around with the position of the provider and ref div, but I keep  getting 0 back.

Any ideas?

Thanks for your help with this.

**Comment by asgvard** [comment]
So every `FocusableElement` is rendered inside a `motion.div`. How do you assign a `ref` inside a `FocusableElement`? It has to be assigned to a top level DOM element, so it will calculate its own coordinate relative to this `motion.div`

**Comment by maidbarion** [comment]
I'm not sure I understand - if I place the provider and ref div top level like this...
```

<FocusContext.Provider value={focusKey}>
      <div ref={ref}>
        <div>
          <div>
            <motion.div>
              {condition && (
                <CollectionFocusable
                ....
```
y is still 0. Is that what you mean?

**Comment by asgvard** [comment]
Ok, let me phrase it differently.
1) `y` of what exactly are you trying to measure? `y` coordinate of the row when it gets focused?
2) What is inside `CollectionFocusable`? How is the `ref` assigned inside that component?

**Comment by maidbarion** [comment]
Ah! Sorry I misread your previous question, and yes you're right. Turns out the ref in CollectionFocusable wasn't top level, so I've adjusted it and it's now working fine. Jjust a bit of misunderstanding on my behalf. Thank you so much for your help with this

**Comment by asgvard** [comment]
You are welcome. Glad it works 👍
