### ISSUE TITLE
A suggestion about keycode mapping

### ISSUE THREAD

**Issue by naygomes** [NoriginMedia/Norigin-Spatial-Navigation#121]
Hello. 
I'm Nayara, I work with developing experiences for hybrid TV and in the last days I had some problemas about spacial navigation.
All experiences that my team develops are tested in a setup with TVs from different manufacturers, each with a different OS. On one of these TVs, spatial navigation wasn't working because it doesn't receive the value of the **_event.keyCode_** attribute or **_event.code_**, it only receives _**event.key**_.
So, I went into the _**[SpatialNavigation.ts](https://github.com/NoriginMedia/Norigin-Spatial-Navigation/blob/main/src/SpatialNavigation.ts)**_ file and noticed that the following function:

```
static getKeyCode(event: KeyboardEvent) {
     return event.keyCode || event.code;
}
```

By changing this function by adding the _**event.key**_ attribute, spatial navigation worked on all TVs, with the function being as follows:

```
static getKeyCode(event: KeyboardEvent) {
     return event.keyCode || event.code || event.key;
}
```

However, as when deploying, the entire package is installed again, this change is lost and continues to not work in production.
Therefore, I wanted to know if it would be possible to add this feature in the next update to make spatial navigation also based on _**event.key**_.

Thank you in advance.

**Comment by xavi160** [comment]
Thank you @naygomes for your suggestion. I've just open a PR to include this change on next releases.

**Comment by naygomes** [comment]
Thanks for answering me. Can you tell me when this change is released?
