### ISSUE TITLE
useFocusable CB on selected/focused child?

### ISSUE THREAD

**Issue by savanesoff** [NoriginMedia/Norigin-Spatial-Navigation#129]
Hi,
I'm curious if there is a way to track currently focused child element?

I'm dealing with the case where the cusom scroll implementation is requiered. For that, I have to know what child is currently in focus/selected.

Looking at the APIs I don't quite see how this is possible.

Is it possible to implement the following?
```ts
const onFocusLeaf = (element) => {
  console.log('currently selected element', element)
}

const {ref} = useFocusable({onFocusLeaf});
...
```
Thank you!

**Comment by xavi160** [comment]
Hello, you should use React for that.

Each focusable leaf has an `onFocus` callback that you can use to propagate the focus change to the parent components. 

```jsx
const Child = ({ onFocus }) => {
  const { ref } = useFocusable({
    onFocus
  });
  return <div ref={ref} />;
};

const Parent = () => {
  const { ref } = useFocusable();
  return (
    <div ref={ref}>
      <Child onFocus={() => console.log('focus 1')} />
      <Child onFocus={() => console.log('focus 2')} />
      <Child onFocus={() => console.log('focus 3')} />
      <Child onFocus={() => console.log('focus 4')} />
      <Child onFocus={() => console.log('focus 5')} />
    </div>
  );
};
```
