### ISSUE TITLE
Support for Philips Titan OS

### ISSUE THREAD

**Issue by Aliendreamer** [NoriginMedia/Norigin-Spatial-Navigation#136]
Hello,
As recently Philips released Saphi OS and the new version with Titan OS for HTML 5 smartv's,
Are there any tests done on such devices or plans to support it? 
I think it should probably work straight out of the way, probably.
Titan os has annoying problem with event propagation but it can be mitigate in ways.

**Comment by xavi160** [comment]
Hello,

Thank you for reaching out.

We have tested this library on Titan OS devices, and it worked fine.

Could you please clarify the issue with event propagation that you are referring to?

**Comment by Aliendreamer** [comment]
hello,
we are planing to use the library.
As for the issues with Titan OS we noticed they handle keydown events a bit strange compared to all other devices,like webos  tizen.
we are in internal discussion with their guys, it is not related to your library, thank you for your answer we can close this one I think.

**Comment by gariasf** [comment]
Hey @Aliendreamer I'm on the dev team at Titan. Can you please expand a bit more on the keydown strangeness? Perhaps we can make this easier for you.

**Comment by predikament** [comment]
I will close this as there are no apparent issues using this library on Titan OS devices.

@Aliendreamer If you do however have any details for @gariasf's investigation purposes then please feel free to reopen this issue or make a new one to share those as applicable. 

Thanks everyone. ☺️

**Comment by prashantchothani** [comment]
@gariasf Possible to share a demo git repo of titanos project for us to start from ? We are starting to develop the app for titan os. For other platforms we used vanilla html and css. Would like to use react as Chrome 84 is good enough case for not using vanilla and make a better app in react

**Comment by gariasf** [comment]
> [@gariasf](https://github.com/gariasf) Possible to share a demo git repo of titanos project for us to start from ? We are starting to develop the app for titan os. For other platforms we used vanilla html and css. Would like to use react as Chrome 84 is good enough case for not using vanilla and make a better app in react

Hi there, here is a link to some TitanSDK examples:

https://github.com/Titan-OS/titan-sdk-examples/
