### ISSUE TITLE
Webos Magic report - onMouseEnter Event not triggering 

### ISSUE THREAD

**Issue by saurav-bhagat** [NoriginMedia/Norigin-Spatial-Navigation#140]
**Describe the bug**
We currently use Norigin spatial Navigation across our html5 platforms - webos, Tizen, coolita, vidaOs TV platforms. And spatial navigation is working perfectly fine. 
We are working on supporting the magic remote in the Webos platform. For that we are trying to focus the element as soon as the cursor reaches the element. 

**To Reproduce**
Given, that our app has the initial setup for keymappings done, this is a test component with 2 buttons. 

To initialize the library:
Here left up right down donates the key map value, 
If I remove the setKeyMap declaration, I get the events as expected. 

```
init({
      debug: false,
      visualDebug: false,
});

 setKeyMap({
       left: LEFT,
       up: UP,
       right: RIGHT,
       down: DOWN,
});
```

```
import { useFocusable, FocusContext } from '@noriginmedia/norigin-spatial-navigation';
import { useEffect } from 'react';

const Button = ({ label, focusKey }: { label: string; focusKey: string }) => {
  const { ref, focused } = useFocusable({ focusKey });

  return (
    <div
      ref={ref}
      className={focused ? 'button-focused' : 'button'}
      onMouseEnter={() => console.log('>>> mouse enter on button')}
      onFocus={() => console.log('>>> focus on button')}
      onBlur={() => console.log('>>>> blur event on button')}
    >
      {label}
    </div>
  );
};

const TestComponent = () => {
  const { ref, focusKey, setFocus } = useFocusable();

  useEffect(() => {
    setFocus('button1');
  }, [setFocus]);

  return (
    <FocusContext.Provider value={focusKey}>
      <div ref={ref}>
        <h1>Test Component</h1>
        <div className="btn-container">
          <Button label={'Button 1'} focusKey="button1" />
          <Button label={'Button 2'} focusKey="button2" />
        </div>
      </div>
    </FocusContext.Provider>
  );
};

export default TestComponent;
```

Using the remote I can easily shift the focus, but invoking the cursor and hovering on any of the buttons does not trigger the onMouseEnter event and the console doesn't get the expected log. 

**Expected behavior**
onMouseEnter should be invoked as soon as the cursor hovers over the element so that we can invoke the `onFocus` method. 

**Screenshots**
Attaching video:

https://github.com/user-attachments/assets/69031a81-eebc-41ac-b947-06beac00f3e3

Could you please help in understanding if there is any gap in understanding the correct implementation flow or any mistake in the code?

Thanks.

**Comment by saurav-bhagat** [comment]
Thanks for the response @predikament .

I was making a silly mistake. Posting the issue which I am facing with my browser here, if this can help someone. 

In the custom responsive devices which we were using for TV testing in the browser were earlier set to Mobile.
We need to change it to Desktop to make this work. 

![image](https://github.com/user-attachments/assets/404f6e7d-4e72-4ff0-8c70-d44a5a0b9ae3)

One question though.
I observed that in TV we are unable to make magic remote work in debug mode, only in non debug mode this runs.
Any reason for this or am I missing something?

**Comment by predikament** [comment]
@saurav-bhagat: Hello again.

> One question though.
> **2 Questions:**

😁

> 1. I observed that in TV we are unable to make magic remote work in debug mode, only in non-debug mode this runs.
Any reason for this or am I missing something?

This works fine for me in Chrome, Firefox and on my WebOS TV:
![image](https://github.com/user-attachments/assets/ae99297c-63d2-49c1-8dc4-ac6f48a532c2)

> 2. How can test the cursorVisibility Event in my browser?

This is documented here: https://webostv.developer.lge.com/develop/guides/system-ui-visibility#visibility-of-the-cursor
And is not really related to this library at all, so I will let you find the rest of the answer yourself.

![](https://cdn.betterttv.net/emote/6557c32ab557529cd35e161a/1x.webp)
