### ISSUE TITLE
whether here has some guide by which tell us how to replace the old react-spatial-navigation with the new 'Norigin-Spatial-Navigation'

### ISSUE THREAD

**Issue by rick-liyue-huang** [NoriginMedia/Norigin-Spatial-Navigation#156]
in my react project, I'm upgrade the old navigation library with the new one, can you please provide me with some guild for that?

**Comment by predikament** [comment]
Hello @rick-liyue-huang,

There is a guide on this in the README here: https://github.com/NoriginMedia/Norigin-Spatial-Navigation?tab=readme-ov-file#examples

Best of luck with your migration work.
