### ISSUE TITLE
[Feature] webOS Magic Remote support

### ISSUE THREAD

**Issue by WEDOBROADCAST** [NoriginMedia/Norigin-Spatial-Navigation#17]
Currently it can run in webOS but only support remote navigational keypad. It will be great if it can support LG magic remote pointer as well.

Thanks

**Comment by predikament** [comment]
@WEDOBROADCAST: Hello! 

We support applications across a wide range of WebOS devices using this library and have seen no need to add anything special to enable interfacing using the LG Magic Remote.

Making this work is as simple as making your element steal the focus when the mouse hovers over it (f.ex. using [`onMouseEnter`](https://www.w3schools.com/jsref/event_onmouseenter.asp)):
```javascript
import React from 'react';
import {useFocusable} from '@noriginmedia/norigin-spatial-navigation';

export default ThisIsFocusableWithTheWebOSMagicRemote = ({onPress}) => {
  const {ref, focused, focusSelf} = useFocusable({
    onEnterPress: onPress
  });

  return (
    <div class={`${focused ? 'focused' : ''}`} onMouseEnter={focusSelf} />
  );
};
```

As such I do not see the need for this issue and will close it accordingly. Best of luck and happy coding!

**Comment by saurav-bhagat** [comment]
Hi @WEDOBROADCAST 
Did this work?

@predikament 
In my application, I have given these events:

```
onMouseOver={() => console.log('>>>> MouseOver 3')}
onMouseEnter={() => console.log('>>>>> Mouse Enter3')}
onMouseDownCapture={() => console.log('>>>>> Mouse Down3')}
```

Tried this in div as well as button element, but not getting these logs in the console when I take the magic remote cursor to these element.
Am I missing something?

**Comment by saurav-bhagat** [comment]
Sure, thanks.
