### ISSUE TITLE
Help Required: Looking for a support on Large List Virtualisation 

### ISSUE THREAD

**Issue by Rajeshr34** [NoriginMedia/Norigin-Spatial-Navigation#18]
I tried different Plugins which currently available on market and i see.. none of them supporting properly one or the other having issues. (like focus not works, scroll not proper, too much code complications )

Can you help me choose the proper one which supports `Norigin-Spatial-Navigation` 

Really sorry to bring this here

Thank you

**Comment by predikament** [comment]
Hello @Rajeshr34!

To tell you the truth, I am honestly not even sure what this question is about.

It was opened a couple of months ago, so I will close this with an assumption that you have figured out your problem.

Feel free to reopen it if you have any issues or questions related to the library, but please provide more details, an example, snippet or some such, so we have a better foundation to understand your problem.

Thanks.
