### ISSUE TITLE
Keydown event on focusable component

### ISSUE THREAD

**Issue by lazarkocic** [NoriginMedia/Norigin-Spatial-Navigation#20]
Is there a way to add keydown event listener on focusable component?
To capture any keydown event, not just enter press, enter release or arrow presses?

**Comment by predikament** [comment]
Hello @lazarkocic 😸 

> Is there a way to add keydown event listener on focusable component?
To capture any keydown event, not just enter press, enter release or arrow presses?

Could you not just add an event-listener to your component for whichever event you want to listen to?
We expose most of the functions you would need to interface with this library through the callback.

Perhaps you could provide some more details, an example or snippet we can use to better understand your problem? ☺️
