### ISSUE TITLE
Previous Element Focused when returning to Component

### ISSUE THREAD

**Issue by stuartflanagan** [NoriginMedia/Norigin-Spatial-Navigation#21]
**Describe the bug**
Focus does not go back to expected element when returning to a component.
It returns to focus the element before the Element expected.
This would be an Implementation issue. Some help on why the element focused before this one is being chosen when returning to the component rather than the one used to leave the component would be great.

The Component has `trackChildren: true`

**Expected behavior**
The component that has focus when moving to another container should be the One that is focused when retuning.

**Comment by predikament** [comment]
Hello @stuartflanagan!

We have such logic ourselves and have not seen this problem, except in some cases where we were unmounting and remounting the component that we expected to have focus, causing it to be "forgotten". 

Could it be that you are remounting the component that you are expecting the focus to fall back to?

If you could please provide an example, snippet or some more details, then we will try to help you out. Thanks!

**Comment by predikament** [comment]
I will close this since it's been relatively stale for a while now. Please feel free to reopen or create a new issue if this is still a problem.

If so, please provide some more details as to your implementation so we can more easily help you troubleshoot.

Thanks!
