### ISSUE TITLE
[question] Unit tests

### ISSUE THREAD

**Issue by serchavalos** [NoriginMedia/Norigin-Spatial-Navigation#23]
Hello!

_(I didn't know where to write this question so I just went with "Bug Report")_

First of all, thank out very much for contributing back to the community! Especially in this very specific context of TV navigation.

I've looked at the code and wonder if there is a specific reason why it doesn't contain any test. If there are no reason, that's totally fine; contributing with unit tests can be an excellent opportunity for any new contributor who would like to participate here.

Cheers!

**Comment by predikament** [comment]
Hello @serchavalos!

> First of all, thank out very much for contributing back to the community! Especially in this very specific context of TV navigation.

Thank you, we appreciate that ☺️ We are happy to contribute and use this library ourselves on a daily basis to help with our implementations.

It does not currently contain any tests. We use this library so extensively, on tens of devices every day, in addition to having StoryBook integrations internally, that we have not really seen to add unit testing as of now.

If you however would like to contribute with a decent unit-testing implementation, or the basis for one, we would most definitely consider including it.

Cheerio!
