### ISSUE TITLE
Get current focusKey on beforePopState

### ISSUE THREAD

**Issue by babysteps** [NoriginMedia/Norigin-Spatial-Navigation#27]
I would like to store the current focusKey in session storage before navigating to a new page (during the beforePopState event), so that I can setFocus() to that focusKey when returning to the page.  I know that the debug mode is spitting this info out to the console, but how can i get it programmatically?

Thanks for such an awesome library!

**Comment by predikament** [comment]
Hello @babysteps!

There is currently no good / clear-cut way of achieving this, but it is actually something that we have been discussing as well, as it's a relatively small change with several potential benefits. As such the plan would be to add this functionality soon.

I will leave this issue open and make sure we update/resolve it, once this change has been put into place.

In the meanwhile I will thank you for your input and wish you happy coding! 😸

**Comment by asgvard** [comment]
Hi!

Yes, as Thomas mentioned, we have been thinking on adding a simple method like "SpatialNavigation.getCurrentFocusKey" to be able to always know what is focused.
Meanwhile you can subscribe to "onFocus" callbacks for the items you wish to store the focus keys for. It might not be the best way if you have a lot of different kinds of items on the screen, but it works 😉

**Comment by babysteps** [comment]
Thank you both for your replies.  I thought about adding all of the onFocus callbacks, but i have a lot of nested FocusContext.Providers and it would be a lot more work to do it that way.  You mentioned that this is something you will be adding "soon".  Do you have a guess as to how long that will be?  If it is more than a couple of weeks I will have to use the callbacks to do this, but I would prefer the new method as it would be a lot easier to integrate.  Thanks again!

**Comment by predikament** [comment]
> Do you have a guess as to how long that will be?

Since it's a relatively small change I will see if I can get this scheduled to be done during next week (but no promises). ☺️

If you don't hear from us at the start / mid of next week then I recommend you resolve it with the onFocus workaround temporarily.

**Comment by babysteps** [comment]
That would be amazing!  I understand it's not promised, but I appreciate you trying.

**Comment by predikament** [comment]
@babysteps: Hello again.

I have addressed this in PR #30 - Let's see what the review-overlords think, then hopefully we can resolve this (as I want this functionality too). ☺️

**Comment by babysteps** [comment]
thanks @predikament!  i really appreciate it.

**Comment by asgvard** [comment]
Hi! This is merged and will be available soon today with a new release 👍

**Comment by babysteps** [comment]
this is fantastic!  thank you all so much.  works perfectly!
