### ISSUE TITLE
Support for webos magic remote

### ISSUE THREAD

**Issue by Aliendreamer** [NoriginMedia/Norigin-Spatial-Navigation#43]
Hello we are looking into the library, to use it in our project.
But previously I remember you didn't have a support for the  LG magic remote, there was such ticket open.
Is this changed now and you support it or is still in the future plans?
And do you accept pull request at one point, if we choose to you this library and write our own wrapper arround it.

**Comment by mikehathsin** [comment]
@Aliendreamer Hello!

Check this: https://github.com/NoriginMedia/Norigin-Spatial-Navigation/issues/17

With this logic, you would already have support for the Magic Remote.

```js
<button
  ref={ref}
  onClick={onEnterPress}
  onMouseEnter={focusSelf}
>
  Click me
</button>
```

**Comment by Aliendreamer** [comment]
thanks for the fast reply, we are just starting our implementation but we will keep this in mind

**Comment by predikament** [comment]
Hello @Aliendreamer and thanks for getting in touch.

> Is this changed now and you support it or is still in the future plans?

As @mikehathsin has already kindly responded (Thank you!), using this library in tandem with the LG Magic Remote is already supported and is something we do in multiple production applications already.

> And do you accept pull request at one point, if we choose to you this library and write our own wrapper arround it.

We accept pull requests for fixes, improvements and general changes that are feasible and useful within the realm of what this (focus) library should be doing. 

If you see any missing functionality that you believe should be included then feel free to open an issue (if you are unsure or would like to discuss anything), or send us a PR. We will do our best to follow up accordingly.

As it looks like this has been fully answered, I will close this issue now.

Best of luck to you, @Aliendreamer! 👽💤
