### ISSUE TITLE
Integration of Norigin Spatial Navigation with Material UI Tree View

### ISSUE THREAD

**Issue by kartikKarekarGSLAB** [NoriginMedia/Norigin-Spatial-Navigation#46]
I wanted to include the **NOrigin Spatial Navigation** with **Material UI's TreeView component**. I want the navigation to be handled with the tree view. User navigates from tree node to the main content section.

Please find the below code snippate for the integration of Material UI Tree view.

1. Tree view is used as a navigation menu.
2.  The main content section will contain a list.

[codesandbox](https://codesandbox.io/s/epic-resonance-hg8psz)

**One more help needed**,

Since we have the concept of **Leaf Focusable elements** and the **Focusable continers**. 

From the application prespective let's say we have enclosed it inside the Focus Container and added the Leaf Focusable nodes.The keyboard interaction callback for a "onArrowPress"  will be handled inside the leaf node. What should be done if we needed to do tha callback should handled in both the callback added inside the leaf focusable node and as well in the Application.

Eg. Referce from the library documentation see, point **"Wrapping Leaf components with a Focusable Container"**

Where we have the layers defined as,
```
Page -> ContentWrapper -> ContentList -> ListItem.
```

We want a common "onArrowPress" will be invoked from the "Page", though we have triggered the event from "ListItem". 

I request @asgvard  @predikament  @LynchyC Please provide inputs on the same.

**Comment by MayurDhande-GSLab** [comment]
Even we are also facing this issue in our application where navigation is not working with `TreeView` component. 
@LynchyC  @predikament  @asgvard can you please look into this ?

**Comment by predikament** [comment]
Hello @kartikKarekarGSLAB.

Thanks for getting in touch.

I have read over your issue a few times now, but I am a still somewhat unsure if I understand what the problem is that you are facing. 

In the example you I can see that the focus is working on some of the items, but there's some issues when navigating between your left and right containers - Is that the issue you are highlighting here?

This library is at its core simply getting the references to these DOM elements and calculating where they are relative to each other based on their  `DOMRect` (https://developer.mozilla.org/en-US/docs/Web/API/DOMRect) values returned that are retrieved using [`Element.getBoundingClientRect()`](https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect).

This means that if there are issues with navigating in certain instances, it could be as simple as being due to elements that are overlapping in unintended ways on specific axis', which cause the library to not be able to understand what should be focused.

**Comment by kartikKarekarGSLAB** [comment]
Hello @predikament 

Thank you adding a respond to the thread,

I will be using this library in my current Project to handle the Spatial Navigation (Since this application being using over Smart TV's and controlled with the input devices like remote,etc). Thank you woking on such a great library that has reduced the efforts for lots of developers .

I really like your guidence on making the effective use of the concepts given by the library like,
1. Focusable Container
2. Leaf Focusable Component

Since I am getting more confused with the same and causing many aligned issue while handling the navigations.

I hopping while the designing and developing the library you guys might have consider the apporches given below library,

- [Spatial Navigation](https://github.com/WICG/spatial-navigation)
- [Spatial Navigation for different Input elements](https://wicg.github.io/spatial-navigation/demo/#input-elements)

It will be really helpful if you provide your valuable inputs in the same. 

Just for your FYI,

The problem we faced to make the Material UI Provided TreeView component Navigable with the NOrigin library.
- [Codesandbox demo for tree view](https://codesandbox.io/s/epic-resonance-hg8psz)

Thank you in Advanced to you and all the team 👍 👍

**Comment by guilleccc** [comment]
Hi @kartikKarekarGSLAB ,

I don't have experience in using Material UI TreeView, but based on the example you provided, it looks like the TreeView has its own focus navigation, which is independent of Norigin-Spatial-Navigation. Thus, when a specific `TreeItem` is focused, the "norigin" focusable is not. So if I am right, you might need to manually set `focusSelf` on the `TreeItem` when the `onNodeFocus` is triggered (https://mui.com/material-ui/api/tree-view/#props).
In our documentation we have an example on how to [use our library in react native environments](https://github.com/NoriginMedia/Norigin-Spatial-Navigation/#using-the-library-in-react-native-environment). I think you might do similarly when you are focusing in a component that use its own navigation.

Regarding the `onArrowPress` "question". I think you should use it only in your "leaf" level. So following your example, you can use onArrowPress as follows:
```
export const RichObjectTreeView = (props: any) => {
  console.log("RichObjectTreeView current props=", props);
  const RenderTree = (props: any) => {
    const { ref, focused, setFocus } = useFocusable({
      onArrowPress: (dir, props, details) => {
        console.log("arrow press", dir, props, details);

        if (dir === "right") { // and any other condition you need
          setFocus("SecondList");
        }

        return true;
      }
    });
    ...
```



Let me know if this makes sense. And this helps you to fix your issue.
