### ISSUE TITLE
Question: keymap for tizen and webOS

### ISSUE THREAD

**Issue by JNuno007** [NoriginMedia/Norigin-Spatial-Navigation#49]
Hi guys, I'm testing my web page in the native browser on a Samsung TV, and I cannot use the D-pad of the remote control.

A mouse icon (pointer) appears instead of moving the focus with the arrows.

How can I change this?

Thanks!

**Comment by predikament** [comment]
@JNuno007: Hello and thanks for getting in touch.

Sorry to hear you're having problems. 

We have never tested this library in the native browser application on Samsung TVs, but if there is a pointer appearing then I assume that is an issue with how the interfacing works in _that_ browser application specifically, more so than an issue in how our library works?

As such I doubt there's much we can do from our library to influence that.

If you do however for any reason find indications that this library is causing the pointer to appear and thus not be usable in such an instance, please let us know and we will do our best to address that.

Thanks and best of luck to you.

**Comment by predikament** [comment]
Hello again, 

> ... As stated in the Readme it says the following: "For as long as the UI/UX is built with the React Framework, it works on the Samsung Tizen TVs, LG WebOS TVs, Hisense Vidaa TVs and a range of other Connected TVs"
> 
> So I thought that this repo supported TV browsers.
> 
> I have tried it in an android TV and a Samsung tizen TV, and I was not successful.
> 
> Thank you.

This is implying _web-based applications_ (e.g. [a Samsung Tizen web app](https://docs.tizen.org/application/web/get-started/tv/first-samsung-tv-app/)), not websites using the browser application.
