### ISSUE TITLE
[Question] Accessibility and focus

### ISSUE THREAD

**Issue by dasilvaluis** [NoriginMedia/Norigin-Spatial-Navigation#58]
Hello! Thank you for this library!

Is there a recommended way to handle a11y? Meaning, for each element that is focused, the TV text-to-speech when activated to read a given label.

At the moment I am working on a project, and the usual approach is to place the `role` and `aria-label` properties on each element. When the component is focused, then the TV reads the label to the user.

Do you have a standard way of handling this outside of what I described? Do you plan to? Maybe even a way to enforce it, as some TV platforms require this functionality.

Would this work?

```js
import { useFocusable } from '@noriginmedia/norigin-spatial-navigation';

function MovieTile({ title, director }) {
  const { ref, focused } = useFocusable();

  return (
    <div ref={ref} role="" arial-label={`${title}, ${director}`} className={focused ? 'movie-focused' : 'movie'}>
      <img src="example" />
      <div>{ title }</div>
      <div>{ director }</div>
    </div>
  );
}
```

**Comment by zemlanin** [comment]
Does [`aria-current`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-current) do what you need?

**Comment by asgvard** [comment]
We have implemented it by manually calling the "text to speech" API when interactable elements getting focus. So for us it looks like this, inside the focusable component:
```javascript
useEffect(() => {
    focused && speak(buttonText);
}, [focused]);
```
where `speak` is an imperative call to the "text to speech" API which might be different for different TV models.
I'm not sure if we will handle or enforce it in this library though as we don't use the default browser `document.activeElement` feature to check the currently focused element. However it may be achieved by applying proper `aria-` attributes to focused elements only, or to "mirror" the `focused` state from our library into the DOM `.focus()` call which will set a browser native focus to the same element. Which in turn should enable a browser TTS engine to speak the element text according to `aria-` lables.

**Comment by asgvard** [comment]
@dasilvaluis Hello! You might be interested in the new Release that includes the sync of the item focus with the native DOM node `.focus()`: https://github.com/NoriginMedia/Norigin-Spatial-Navigation/releases/tag/v1.3.0
Now you can simply enable it for all focusable items and use `aria` tags for accessibility.

**Comment by dasilvaluis** [comment]
That sounds great! thank you!
