### ISSUE TITLE
[Question] What is the defined behavior for when `useFocusable` is used without passing `ref`?

### ISSUE THREAD

**Issue by adri326** [NoriginMedia/Norigin-Spatial-Navigation#68]
Hello and thank you for this very useful library!

Last week, I tried to have a component override a little bit of the of the behavior of the arrow keys, and for that I needed to use `setFocus`. However, I didn't need any of the other functionalities in that component, and so I was curious to know if I could've skipped passing the `ref` to an element and just use `setFocus` that I receive from `useFocusable`.

This seemed to work, but the documentation does not specify what the defined behavior is for when `useFocusable` is used without passing `ref` to an element, hence my question. So I wanted to know if things would be breaking in the future if I left this call to `useFocusable` without passing `ref`.

**Comment by msalafia** [comment]
@predikament if i need an imperative call to `setFocus` from an effect of a Component that is not focusable the only way i have to get the method `setFocus` is using the hook `useFocusable ` inside such Component. Following what @adri326 suggest, is it correct using `useFocusable` without using the `ref` it returns to retrieve `setFocus` or is there any other way to imperatively call `setFocus` from a non-Focusable Component?
