### ISSUE TITLE
Remove enter button

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [NoriginMedia/Norigin-Spatial-Navigation#69]
**Is your feature request related to a problem? Please describe.**
I don't think the enter button is related to navigation. Like https://github.com/NoriginMedia/Norigin-Spatial-Navigation/pull/56#issuecomment-1406612587, a keydown listener that checks if the element is focused can be used instead of an enter press.

**Describe the solution you'd like**
Remove enter key from key map, and remove other inputs related to enter button.

**Describe alternatives you've considered**
N/A

**Additional context**
Related to https://github.com/NoriginMedia/Norigin-Spatial-Navigation/pull/56#issuecomment-1406612587

**Comment by predikament** [comment]
Hello @ChocolateLoverRaj.

Thanks for sharing your opinion.

From our viewpoint we have seen no need to explicitly remove this, as it's a less verbose interface to achieve the functionality of handling the enter-presses of the focusable elements, with basically no downsides.

If you do however wish to not use this functionality then it is a simple matter of not defining the `onEnterPress` callback -
In which case you can add your own listeners to achieve your intended functionality.

Best of luck to you!
