### ISSUE TITLE
Export `navigateByDirection`

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [NoriginMedia/Norigin-Spatial-Navigation#70]
**Is your feature request related to a problem? Please describe.**
I want to do navigation with a gamepad

**Describe the solution you'd like**
Export `navigateByDirection`, like the other methods are exported.

**Describe alternatives you've considered**
Current work-around:
```ts
import { SpatialNavigation } from '@noriginmedia/norigin-spatial-navigation'

declare module '@noriginmedia/norigin-spatial-navigation' {
  const SpatialNavigation: any
}
```

**Additional context**
Related to #67

**Comment by predikament** [comment]
Hello @ChocolateLoverRaj.

Thanks for your contribution.

When it comes to `navigateByDirection`, this is already exposed through the `useFocusable` hook, as you can see here: https://github.com/NoriginMedia/Norigin-Spatial-Navigation/blob/main/src/useFocusable.ts#L208

This is also mentioned here: https://github.com/NoriginMedia/Norigin-Spatial-Navigation#top-level-exports

You can also directly call it on the service:

```javascript
import { SpatialNavigation } from '@noriginmedia/norigin-spatial-navigation'

..
SpatialNavigation.navigateByDirection(..); // This works too
..
```

So I believe what you are requesting is already there. As such I will close this as "Won't fix".

Thanks.

**Comment by ChocolateLoverRaj** [comment]
@predikament The code you commented:
```ts
import { SpatialNavigation } from '@noriginmedia/norigin-spatial-navigation'
```
This creates a typescript error because `SpatialNavigation` isn't exported in the TypeScript definitions.

**Comment by predikament** [comment]
Hello again, @ChocolateLoverRaj

Based on your latest comment I now understand what you are trying to communicate:
> ... This creates a typescript error because `SpatialNavigation` isn't exported in the TypeScript definitions.

I thought the issue you were describing was related to what you had mentioned in the title and description here: 
> **Export navigateByDirection, like the other methods are exported.**

So I misunderstood, but you mean the library's service itself and how _that_ is exported - Then it's more clear.

OK, I see the same issue - We will add it to our backlog and get it addressed. Thanks for letting us know!

In the meanwhile your workaround should be fine to use. (Alternatively you use the hook, where you should have no such issues.)
