### ISSUE TITLE
A way to identify when setFocus is called with a non-existing key

### ISSUE THREAD

**Issue by jeyvega** [NoriginMedia/Norigin-Spatial-Navigation#71]
**Is your feature request related to a problem? Please describe.**
Error calling `setFocus(MyFocusKey)` with a non-existing focus key. In this case the focus will lose but there is no easy way to identify when it happens (when the focus key doesn't exist or when the setFocus with that key fails).

**Describe the solution you'd like**
It'd be helpful to get in somehow when the focus is set to a non-existing key or any way to identify when a key doesn't exist previous to call `setFocus(..)` so if we know it doesn't exist we don't try to focus it.

**Describe alternatives you've considered**
* a second param to `setFocus` to send a callback in case the focus key is not found
* Someway to get if there is an element with an specific focus key

**Additional context**
Currently, my team is using Noring Spatial Navigation and we found the next scenario:
1. There is a list of components (cards) that come from an API so we set keys depending on the name
2. If a user clicks over a card, the list is unmounted and we redirect the user to another page (we save in the state the last focused card)
3. When the user goes back to the list of items we set the focus to the last focused card saved in the state

With this scenario in mind, sometimes when we call `setFocus(MyFocusKey)` the key doesn't exist in the list of cards fetched from the API therefore the focus is lost.

I have tried to identify when the focus is lost but even calling `getCurrentFocusKey` it returns the non-existing focus.

**Comment by guilleccc** [comment]
Hi @jeyvega ,

Thanks for your contribution.

The issue you describe here may be a limitation of `setFocus`, as it shouldn't be invoked with a non-existing key. So I think you'll need to fix the problem with having a wrong focus-key first.
If you go back to the list of items (step 3), you could recreate the same elements with the same key, and then theoretically it would work.
I would recommend that if the error persists, you try using [react-navigation](https://github.com/react-navigation/react-navigation). This library allows you to push a new screen on the stack, and when you go back, you don't have to recreate the page (the list of items will be there).
As I said, it should work if you recreate the page when going back, regardless of the router library used.


Regards

**Comment by asgvard** [comment]
Hello!

Indeed it seems to be more related to the specific scenario when you go back to the page with dynamically loaded items and the previously stored key might not exist.
There is a couple of solution I could think of:
1) Before calling `setFocus` when you go back, make sure it exists by iterating over items and trying to find the item with the previously stored key. It's not super optimal, but gives you opportunity to check if it exists before focusing it.
2) You can utilize `preferredChildFocusKey` feature where you can store the `preferred` key, and in the worst case if it doesn't exist, it will focus the first one.

We might think about some "safety" checks to help the app developers to identify such cases when `setFocus` is called with a wrong/non-existent focus key, but as a workaround perhaps you could use `getCurrentFocusKey` method to see if the returned focus key is the same as what you have sent into `setFocus` method. If it's different, that means the focus has not been set correctly. I haven't tried it myself, so it's just an idea :)
