### ISSUE TITLE
Spatial navigation with dropdown select

### ISSUE THREAD

**Issue by m-a-saleh** [NoriginMedia/Norigin-Spatial-Navigation#76]
Dear all,

I have trouble trying to make Norigin-Spatial-Navigation work with the dropdown select element.

I want the following typical behavior:
-The dropdown button could get focused with directional navigation.
-When focused, pressing Enter will expand the dropdown menu.
-When the menu is expanded, pressing the up and down keys will highlight the different dropdown options.
-When Enter is pressed, the highlighted option is selected, the dropdown is retracted, and the onSelect callback function is called.

I have tried making the dropdown component focusable as follows:

```
import {useFocusable} from "@noriginmedia/norigin-spatial-navigation";

function DropdownSelection() {

    const { ref, focused } = useFocusable()

    return (
        <select ref={ref} name="cars" id="cars">
            <option value="volvo">Volvo</option>
            <option value="saab">Saab</option>
            <option value="mercedes">Mercedes</option>
            <option value="audi">Audi</option>
        </select>
    );
}

export default DropdownSelection;
```
But this did not work. The menu does not expand on  Enter press when the element is focused.

I even tried with dropdown components from libraries like Semantic-ui and react-bootsrap, but also failed.

Any suggestions?

**Comment by asgvard** [comment]
Hello.

First of all, you need to handle `onEnterPress` callback from the `useFocusable` hook. Otherwise, nothing is happening when Enter is pressed. Then each Option element needs to be a focusable component as well with its own `onEnterPress` handling. Hope it helps.

**Comment by jbright716** [comment]
I separated the option out to its own component but I am now facing an issue with the focus being lost once i get to the select. 

```
import {useFocusable} from "@noriginmedia/norigin-spatial-navigation";

function DropdownOption() {
	const { ref, focused } = useFocusable({onEnterPress: () => //}}
    return (
        <option ref={ref} value={value}>{label}</option>
    );
}
function DropdownSelection() {
	const { ref, focused } = useFocusable({onEnterPress: () =>  })
    return (
        <select ref={ref} name="cars" id="cars">
            <DropdownOption value=“volvo” label=“Volvo”/>
            <DropdownOption value=“mercedes” label=“Mercedes”/>
            <DropdownOption value=“audi” label=“Audio”/>
        </select>
    );
}

export default DropdownSelection;
```
