### ISSUE TITLE
useFocusedContext filename fix.

### ISSUE THREAD

**Issue by nihalvaria** [NoriginMedia/Norigin-Spatial-Navigation#84]
Issue: 
The file should match with what is being exported. 
We export `useFocusContext` hook and filename is `useFocusedContext`

Resolution :
I have branch ready with the fix. Please guide how to contribute.

**Comment by asgvard** [comment]
Hi. I've renamed it as part of the latest patch release, it's a minor thing. Available in v1.3.2 :)
