### ISSUE TITLE
Support for RTL

### ISSUE THREAD

**Issue by jeev1989** [NoriginMedia/Norigin-Spatial-Navigation#88]
**Describe the bug**
On RTL looks like the initial focus on the swimlane is not being picked properly, also key navigation which needs to be reveresed.

**To Reproduce**
1. Load the demo app, change the body dir to rtl
2. navigate left from the menu to bring the focus on the swimlanes
3. Observe the current focused element, this is not the expected element

**Expected behavior**
Focused element is the 7th item(sn:focusable-item-28) in the swimlane, where as it should have been the first.

**Screenshots**
<img width="1207" alt="Screenshot 2023-07-31 at 5 47 42 PM" src="https://github.com/NoriginMedia/Norigin-Spatial-Navigation/assets/3212790/9b8eb27c-63d4-4bc0-bbc1-e2c30f51316b">

**Additional context**
Is RTL support expected/planned for this library? It would be a good feature if it supports RTL on the fly.

**Comment by jeev1989** [comment]
@asgvard @zemlanin @eigil @hans00 : Can anybody please let me know if you guys are aware of such an issue?

**Comment by sarah-harissa-dotcom** [comment]
There are issues on RTL, is there a way to fix it?

**Comment by jeev1989** [comment]
[Add support for RTL #96 ](https://github.com/NoriginMedia/Norigin-Spatial-Navigation/pull/96) seems to be working as expected as per the issue reported by me. 
Kindly request @asgvard @zemlanin @eigil @hans00 to checkout the PR and update if changes are good.

**Comment by Braggiouy** [comment]
**Status Update:**

The pull request [Add support for RTL](https://github.com/NoriginMedia/Norigin-Spatial-Navigation/pull/96) has been approved. It will be incorporated into the upcoming release, effectively addressing the associated issue.

**Comment by sarah-harissa-dotcom** [comment]
Awesome, thanks for the update!

**Comment by jeev1989** [comment]
Thanks alot guys..
