### ISSUE TITLE
Unable to prevent or recover from lost focus

### ISSUE THREAD

**Issue by mbret** [NoriginMedia/Norigin-Spatial-Navigation#89]
**Is your feature request related to a problem? Please describe.**
I need to restore focus between navigation with react router. Because it mount / unmount on every route change, there is a chance a focus might not exist.

Additionally and I think this is the bigger problem, it's dangerous to not have a way to recover from lost focus as a focus element might appear / disappear dynamically (such as after a query refresh). This is not something we can control unless we have a dedicated API to check if a focus exist before going for it.

**Describe the solution you'd like**
Either something to check if a focus key exist in the tree or a way to fallback on some other key

**Describe alternatives you've considered**
I've considered attaching a data-focus-key to every component I can focus and do a manual DOM check to assert whether an element exist or not. This is heavy and forces us to manually attach a focus key to every element.

**Additional context**
None

**Comment by predikament** [comment]
Hello! 

This [change](https://github.com/NoriginMedia/Norigin-Spatial-Navigation#doesfocusableexist-function-focuskey-string--boolean) in [v2.0.0](https://github.com/NoriginMedia/Norigin-Spatial-Navigation/releases/tag/v2.0.0) (which was just released a week ago) could hopefully help with your issue.

Let us know if that would be sufficient to resolve this issue. 

Thanks!

**Comment by mbret** [comment]
This is awesome, the checker function together with global setFocus was such a pain point for us. Im really thankful for your update.

**Comment by predikament** [comment]
Glad to hear it helps with your issue and sorry for not getting back to you sooner; Busy days.

I will close this issue accordingly now, but please file any new issues you might think we should be aware of.

Thanks!
