### ISSUE TITLE
Scrolling not working

### ISSUE THREAD

**Issue by AmirKaftari** [NoriginMedia/Norigin-Spatial-Navigation#99]
**Describe the bug**
I use <FocusContext.Provider value={focusKey}>, focused and change focuse happened but scroll not happened in react js.

**Comment by AmirKaftari** [comment]
tnx.
can i set list start from right?

**Comment by predikament** [comment]
Hi @AmirKaftari!

I'm sorry, but I don't think we can help you with any specific answers based on your code snippet alone

If you need to do something _scroll_ related then I recommend you look into the documentation for these things:
- [(Document) scroll event](https://developer.mozilla.org/en-US/docs/Web/API/Document/scroll_event)
- [(Spatial Navigation) `navigateByDirection(..)`](https://github.com/NoriginMedia/Norigin-Spatial-Navigation/#navigatebydirection-function-direction-string-focusdetails-focusdetails--void)
- [(Element) `scrollTo(..)`](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollTo)

This is what we use when implementing the library in client applications ourselves and it is relatively straight forward. 

Best of luck to you.

Closing this issue as it's
